name: ask-me:workflow
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: appleboy/ssh-action@v1.0.3
    - name: Install Dependencies
      run: "npm install"
    - name: run test
      run: "npm run test "
