name: ask-me:workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push] # Trigger the workflow on push events to main branch

# on: use this specify branches  to trigger the workflow, develop, feature 
#   push:
#     branches:
#     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: "npm install"
    - name: run test
      run: "npm run test "
